name: CI
on:
  pull_request:
env:
  SCALAC_FATAL_WARNINGS: true
  PACKAGE_TOKEN: ${{ secrets.avibryant }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: scalafmt
        - uses: actions/checkout@v1
        - uses: olafurpg/setup-scala@v7
        - run: git config --global github.actor avibryant
        - run: sbt scalafmtCheck
      - name: test
        - uses: actions/checkout@v1
        - uses: olafurpg/setup-scala@v7
        - run: git config --global github.actor avibryant
        - run: sbt '+test'
      - name: package
        - uses: actions/checkout@v1
        - uses: olafurpg/setup-scala@v7
        - run: git config --global github.actor avibryant
        - run: sbt publish