name: CI
on:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v7
    steps:
      - name: scalafmt
        - run: git config --global github.actor avibryant
        - run: sbt scalafmtCheck
      - name: test
        env:
              SCALAC_FATAL_WARNINGS: true
        - run: git config --global github.actor avibryant
        - run: sbt '+test'
      - name: package
        env:
          PACKAGE_TOKEN: ${{ secrets.avibryant }}
        - run: git config --global github.actor avibryant
        - run: sbt publish