name: CI
on:
  pull_request:
jobs:
  test:
    name: ${{ matrix.command }} ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [adopt@1.8, adopt@1.11]
        command:
          - "'++2.11.12 test'"
          - "'++2.12.10 test' scripted"
          - "'++2.13.1 test'"
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java }}
      - run: sbt ${{ matrix.command }}