name: CI
on:
  pull_request:
env:
  SCALAC_FATAL_WARNINGS: true
  BINTRAY_USER: ${{ secrets.bintrayuser }}
  BINTRAY_PASS: ${{ secrets.bintraypass }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
      - name: scalafmt
        run: sbt scalafmtCheck
      - name: test
        run: sbt '+test'
      - name: package
        run: sbt publish