name: CI
on:
  pull_request:
jobs:
  test:
    name: ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - "2.11.12"
          - "2.12.10"
          - "2.13.1"
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.8
      - run: sbt '++ ${{ matrix.version }} test'